# Generated by Django 5.0.1 on 2024-01-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_details', models.TextField()),
                ('user_information', models.CharField(max_length=255)),
                ('ticket_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
