# Generated by Django 5.0.1 on 2024-01-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='jira_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
