# Generated by Django 5.0.1 on 2024-01-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_jira_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='incident_details',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_information',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(default='Task', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='summary',
            field=models.CharField(default='', max_length=255),
        ),
    ]
